### ISSUE TITLE
error: reference to undefined identifier ‘syscall.NAME_MAX’

### ISSUE THREAD

**Issue by danil-demidov** [hoffie/multilog_exporter#4] opened 2021-04-09 14:25 UTC
# go get -u github.com/hoffie/multilog_exporter
# github.com/hoffie/multilog_exporter/vendor/github.com/fstab/grok_exporter/tailer/fswatcher
/home/yva/go/src/github.com/hoffie/multilog_exporter/vendor/github.com/fstab/grok_exporter/tailer/fswatcher/fseventProducerLoop_linux.go:64:24: error: reference to undefined identifier ‘syscall.NAME_MAX’
    bytes     *[syscall.NAME_MAX]byte
                        ^
/home/yva/go/src/github.com/hoffie/multilog_exporter/vendor/github.com/fstab/grok_exporter/tailer/fswatcher/fseventProducerLoop_linux.go:65:65: error: reference to undefined identifier ‘syscall.NAME_MAX’
    buf       = make([]byte, (syscall.SizeofInotifyEvent+syscall.NAME_MAX+1)*10)
                                                                 ^
/home/yva/go/src/github.com/hoffie/multilog_exporter/vendor/github.com/fstab/grok_exporter/tailer/fswatcher/fseventProducerLoop_linux.go:97:25: error: reference to undefined identifier ‘syscall.NAME_MAX’
      bytes = (*[syscall.NAME_MAX]byte)(unsafe.Pointer(&buf[offset+syscall.SizeofInotifyEvent]))

**Comment by hoffie** [comment] 2022-01-06 07:49
I've just updated the vendored dependencies and can't reproduce this anymore (but hadn't seen the issue before either). Therefore, I'm closing this for now. Please re-open if you still see issues.

**Closed as completed by hoffie** 2022-01-06 07:49 UTC
